[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pycryptoex"
dynamic = ["version"]
description = "A library providing a clients for interacting with various APIs of cryptocurrency exchanges for trading and accessing market data"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.9"
authors = [
  { name = "ren3104", email = "2ren3104@gmail.com" },
]
keywords = [
  "crypto",
  "cryptocurrency",
  "exchange",
  "trade",
  "trading",
  "bitcoin",
  "altcoin",
  "api",
  "api-client",
  "websocket",
  "async",
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Framework :: AsyncIO",
  "Intended Audience :: Developers",
  "Intended Audience :: Financial and Insurance Industry",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Office/Business :: Financial",
  "Topic :: Software Development :: Libraries",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Typing :: Typed",
]
dependencies = [
  "aiohttp>=3.9.0",
  "typing-extensions>=4.0.0 ; python_version < '3.11'",
]

[project.optional-dependencies]
speedup = ["orjson"]
crypto = ["cryptography>=42.0.0"]

[project.urls]
Homepage = "https://github.com/ren3104/pycryptoex"
Repository = "https://github.com/ren3104/pycryptoex"
"Bug Tracker" = "https://github.com/ren3104/pycryptoex/issues"

[tool.hatch.version]
path = "pycryptoex/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["pycryptoex"]

[tool.hatch.envs.default]
dependencies = ["pre-commit", "ruff", "mypy"]
post-install-commands = ["pre-commit install"]

[tool.hatch.envs.types]
features = ["speedup", "crypto"]
extra-dependencies = ["mypy==1.11.2"]

[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:pycryptoex}"

[tool.hatch.envs.hatch-static-analysis]
config-path = "none"
dependencies = ["ruff==0.16.5"]

[tool.hatch.envs.hatch-static-analysis.scripts]
format-check = "ruff format{env:HATCH_FMT_ARGS:} --check --diff {args:.}"
format-fix = "ruff format{env:HATCH_FMT_ARGS:} {args:.}"
lint-check = "ruff check{env:HATCH_FMT_ARGS:} {args:.}"
lint-fix = "ruff check{env:HATCH_FMT_ARGS:} --fix {args:.}"

[tool.ruff]
line-length = 88
target-version = "py39"

[tool.ruff.lint]
select = [
  "ANN",
  "B",
  "C4",
  "E",
  "F",
  "PYI",
  "RUF",
  "SIM",
  "UP",
  "W",
]
ignore = [
  "ANN401",
  "B027",
  "RUF023",
]

[tool.mypy]
strict = true
warn_unreachable = true

[[tool.mypy.overrides]]
module = ["orjson"]
ignore_missing_imports = true
